using UnityEngine.InputSystem;
using AutoGenerated.Input;
using Controllers.Monobehaviours.Abstracts;

namespace Controllers.Monobehaviours
{
    public class RocketController : Controller
    {
        private ControllerInput _input;

        private void Awake()
        {
            _input = new ControllerInput();
        }

        private void OnEnable()
        {
            var controller = _input.Controller;
            if (_thrustCommand is { })
            {
                var action = controller.Thrust;
                action.performed += OnThrust;
            }

            if (_rotateCommand is { })
            {
                var action = controller.Rotation;
                action.performed += OnRotate;
            }

            _input.Enable();
        }

        private void OnDisable()
        {
            var controller = _input.Controller;
            if (_thrustCommand is { })
            {
                var action = controller.Thrust;
                action.performed -= OnThrust;
            }

            if (_rotateCommand is { })
            {
                var action = controller.Rotation;
                action.performed -= OnRotate;
            }

            _input.Disable();
        }

        private void OnThrust(InputAction.CallbackContext input)
        {
            ThrustInput = input.ReadValue<float>();
            _thrustCommand!.Execute();
        }

        private void OnRotate(InputAction.CallbackContext input)
        {
            RotateInput = input.ReadValue<float>();
            _rotateCommand!.Execute();
        }
    }
}
