using UnityEngine;
using UnityEngine.InputSystem;
using Monobehaviours.BaseClasses;
using AutoGenerated.Input;

namespace Monobehaviours.Controllers
{
    public class RocketController : Controller
    {
        private ControllerInput _controllerInput;

        private void OnMovement(InputAction.CallbackContext input)
        {
            var value = input.ReadValue<Vector2>();
            MovementInput = new Vector3(value.x, value.y, 0);
            _movementCommand!.Execute();
        }

        private void Awake()
        {
            _controllerInput = new ControllerInput();
        }

        private void OnEnable()
        {
            if(_movementCommand is { })
            {
                _controllerInput.Controller.Movement.performed += OnMovement;
            }

            _controllerInput.Enable();
        }

        private void OnDisable()
        {
            if (_movementCommand is { })
            {
                _controllerInput.Controller.Movement.performed -= OnMovement;
            }

            _controllerInput.Disable();
        }
    }
}
